# This is a basic workflow to help you get started with Actions

name: Notify New Issues

# Controls when the workflow will run
on:
  # Triggers the workflow on comment events on pending response issues
  issues:
    types: [opened]

# Limit the GITHUB_TOKEN permissions
permissions: {}

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "notify"
  notify:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a single command using the runners shell
      - name: Run sample command
        run: |
          title="${{github.event.issue.title}}"          
          if [[ $title =~ ^octocat ]]; then
          echo "PR title starts with 'octocat'"
          exit 0
          else
          echo "PR title did not start with 'octocat'"
          exit 1
          fi
